### PR TITLE
Base work on the faction points tracking.

### PR DESCRIPTION
**Pull request by battis124**
- I added base counter for faction points.
- added timer
 - Also i have changed Fame, ReSpec, Silver counters to display gained value per session, IMO no need to display account values in statistic
 
 https://i.gyazo.com/1819c02233eb1222a6f17915346f4815.png

### CODE REVIEW

**Comment by Triky313** [comment]
Cool thing, I'll look at this asap and then merge it. :)

**Comment by Triky313** [comment]
Your pull request is a very good approach.
I've already adjusted a few small things.
In any case, what still needs to be included are all other fractions. In addition, the tracker has to look a little better.

I'll see how I can incorporate your approach, but it currently needs a revision.

**Comment by battis124** [comment]
Sure, maybe just create a new branch for faction points and i will post my changes there.
I'm not C# dev, so i know my code need some improvements, but i wanted to share my work, so you could do something cool with it int he future ;)
I also needed quickly a counter for faction points for the new patch.

About displaying other factions - There is some information about current faction in the factionStandingUpdate event, so we can do something with it. I listed which ID is which faction but i did it before new update and it need to be tested again.

**Comment by Triky313** [comment]
All right. I'll have a look at it for the next few days, we'll get something useful.

**Comment by Triky313** [comment]
Features were added through a different branch.

Thank you for your Work. :)

**Pull request closed without merging**
